codecov:
  max_report_age: off

coverage:
  status:
    project:
      core:
        target: auto
        flags:
          - nevoCore

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes
  branches: null

flags:
  nevoCore:
    paths:
      - nevojs-core/coverage/coverage-final.json
    carryforward: true
